Clean up lint errors and add documentation to kaldb_configs.proto
slackhq/kaldb pull request #222
Opened 2022-02-03 18:07 UTC by mansu

Clean up lint errors and add documentation to kaldb_configs.proto

2022-02-04 17:42 UTC, vthacker commented
+0 to this. How will we catch linter errors in the future? 

I think if we do this let's make sure the linter rule that you used is added as a pre-commit step

2022-02-04 23:00 UTC, bryanlb requested changes
If we're doing this I think we should apply the cleanup to all files instead of just one. I'd also like to see this made part of the build process validation if we're going to introduce this.

2022-02-04 23:04 UTC, mansu commented on kaldb/src/main/proto/kaldb_configs.proto
> +  int64 max_offset_delay = 9;
Thought I deleted it. Dropped it now.

2022-02-04 23:07 UTC, mansu commented
I agree with doing a better job at this. Adding the protolint now is quite a bit of yak shaving so let's tackle it at a different time. Opened an issue for it https://github.com/slackhq/kaldb/issues/225.

2022-02-04 23:17 UTC, vthacker submitted a review, later dismissed

2022-02-07 16:54 UTC, bryanlb approved these changes
:shipit:

2022-02-07 17:36 UTC, merged