Emit metrics for metdata stores
slackhq/kaldb pull request #337
Opened 2022-07-12 00:30 UTC by mansu

Emit guages to measure the size of metadata stores.

2022-07-12 19:04 UTC, bryanlb requested changes
Couple issues noted with the specific implementations, but I believe there is a larger issue with this approach. 

As it exists today there are times where the cache does not accurately reflect the values that are present in ZK. Specific to this use case we are primarily concerned about startup and shutdown. This code will have an expected race condition where inaccurate counts are expected at boot and potentially shutdown, due to the lag the cache will observe.

2022-07-13 03:40 UTC, mansu commented on kaldb/src/main/java/com/slack/kaldb/clusterManager/RecoveryTaskAssignmentService.java
> +        Tags.empty(),
Fixed.

2022-07-13 03:40 UTC, mansu commented on kaldb/src/main/java/com/slack/kaldb/clusterManager/ReplicaCreationService.java
> +        "replica_nodes_size",
Leaving these strings as is since they are only used once.

2022-07-13 03:41 UTC, mansu commented on kaldb/src/main/java/com/slack/kaldb/clusterManager/ReplicaAssignmentService.java
> +        "cache_slots_size",
Leaving these strings as is since they are only used once.

2022-07-13 03:41 UTC, mansu commented on kaldb/src/main/java/com/slack/kaldb/clusterManager/RecoveryTaskAssignmentService.java
> +    meterRegistry.gauge(
Leaving these strings as is since they are only used once.

2022-07-13 03:41 UTC, mansu commented
Moved the guages into a new `ClusterMonitorService` class as discussed.

2022-07-13 17:18 UTC, bryanlb approved these changes

2022-07-13 17:20 UTC, merged