Add a unit test for KaldbQueryParser
slackhq/kaldb pull request #467
Opened 2023-02-07 16:40 UTC by mansu

Add a unit test for KaldbQueryParser.

2023-02-07 16:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slackhq/kaldb?pullRequest=467) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slackhq/kaldb?pullRequest=467) before we can accept your contribution.<br/><hr/>**Suman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slackhq/kaldb?pullRequest=467) it.</sub>

2023-02-07 18:47 UTC, vthacker submitted a review, later dismissed

2023-02-07 18:49 UTC, bryanlb requested changes
Looks good on the code end. Can we get the commit authorship fixed so that the CLA is resolved?

2023-02-09 17:04 UTC, bryanlb approved these changes

2023-02-09 17:04 UTC, merged