Vthacker/timesinceepoch date
slackhq/kaldb pull request #588
Opened 2023-06-26 23:46 UTC by vthacker

###  Summary

Builds on top of https://github.com/slackhq/kaldb/pull/587 to ensure we can make date range queries

2023-06-28 16:59 UTC, bryanlb requested changes

2023-06-28 16:59 UTC, bryanlb commented on kaldb/src/test/java/com/slack/kaldb/logstore/opensearch/OpenSearchQueryParserTest.java
> +public class OpenSearchQueryParserTest {
This doesn't seem like it should be in a new test class - this should probably go with the other logsearcher.search behavior, in the `LuceneIndexStoreImplTest`

2023-06-28 16:59 UTC, bryanlb commented on kaldb/src/main/java/com/slack/kaldb/logstore/opensearch/OpenSearchAdapter.java
> +        // This is a quick workaround to ensure we can do data range queries on the timestamp field
Let's convert this to the todo syntax so it's flagged in IntelliJ

2023-06-28 16:59 UTC, bryanlb commented on kaldb/src/test/java/com/slack/kaldb/logstore/search/LogIndexSearcherImplTest.java
> +    DateTimeFormatter formatter = DateTimeFormatter.ISO_INSTANT;
If I recall correctly, there was some difficulty in getting the return values here to work nicely with Grafana histogram rendering. We should verify that changing the response date format here isn't breaking the histogram rendering for Grafana.

2023-06-28 21:50 UTC, fxchen commented
Prototype from CLI (AI code review)


1. The test method `testRangeQueryOnTimestampField` should be annotated with `@ExtendWith(MockitoExtension.class)` to enable mocking.

2. The test method `testRangeQueryOnTimestampField` should be modified to use the `logStoreAndSearcherRule.logStore.addMessage` method instead of the deprecated `logStoreAndSearcherRule.logStore.add` method.

3. The test method `testRangeQueryOnTimestampField` should be modified to use `assertThat(results.hits).hasSize(1)` instead of `assertThat(results.hits.size()).isEqualTo(1)`.

4. The test method `testRangeQueryOnTimestampField` should be modified to use `assertThat(bucket1AsLong).isGreaterThanOrEqualTo(time.toEpochMilli())` instead of `assertThat(Long.parseLong(histogram.getBuckets().get(0).getKeyAsString()) >= time.toEpochMilli()).isTrue()`.

5. The test method `testRangeQueryOnTimestampField` should be modified to use `assertThat(bucket2AsLong).isLessThanOrEqualTo(time.plusSeconds(10).toEpochMilli())` instead of `assertThat(Long.parseLong(histogram.getBuckets().get(1).getKeyAsString()) <= time.plusSeconds(10).toEpochMilli()).isTrue()`.

```diff
@@ -0,0 +1,45 @@
+package com.slack.kaldb.logstore.opensearch;
+
+import static com.slack.kaldb.testlib.MessageUtil.TEST_DATASET_NAME;
+import static com.slack.kaldb.testlib.MessageUtil.makeMessageWithIndexAndTimestamp;
+import static org.assertj.core.api.Assertions.assertThat;
+
+import brave.Tracing;
+import com.slack.kaldb.logstore.LogMessage;
+import com.slack.kaldb.logstore.search.SearchResult;
+import com.slack.kaldb.testlib.TemporaryLogStoreAndSearcherExtension;
+import java.io.IOException;
+import java.time.Instant;
+import java.time.temporal.ChronoUnit;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.ExtendWith;
+import org.junit.jupiter.api.extension.RegisterExtension;
+import org.mockito.junit.jupiter.MockitoExtension;
+
+@ExtendWith(MockitoExtension.class)
+public class OpenSearchQueryParserTest {
+
+  @RegisterExtension
+  public TemporaryLogStoreAndSearcherExtension logStoreAndSearcherRule =
+      new TemporaryLogStoreAndSearcherExtension(false);
+
+  public OpenSearchQueryParserTest() throws IOException {
+    Tracing.newBuilder().build();
+  }
+
+  @Test
+  public void testRangeQueryOnTimestampField() {
+    Instant time = Instant.now();
+    Instant timeMinus5 = time.minus(5, ChronoUnit.MINUTES);
+    logStoreAndSearcherRule.logStore.addMessage(
+

2023-07-24 20:39 UTC, bryanlb commented
See #625

2023-12-14 18:11 UTC, closed without merging